.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitzeny_qt test_bitzeny_qt
clean: FORCE
	$(MAKE) -C .. bitzeny_qt_clean test_bitzeny_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitzeny_qt_check
bitzeny-qt bitzeny-qt.exe: FORCE
	 $(MAKE) -C .. bitzeny_qt
